"""create ci_timeseries and hardware_specs tables

Revision ID: 764000c99946
Revises: fd8d315c4856
Create Date: 2026-07-17 22:37:23.867400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764000c99946'
down_revision: Union[str, Sequence[str], None] = 'fd8d315c4856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
