"""create ci_timeseries and hardware_specs tables

Revision ID: fd8d315c4856
Revises: 
Create Date: 2026-07-17 22:29:59.490906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8d315c4856'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_timeseries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ci_gco2e_per_kwh', sa.Float(), nullable=False),
    sa.Column('coal_pct', sa.Float(), nullable=True),
    sa.Column('hydro_pct', sa.Float(), nullable=True),
    sa.Column('wind_pct', sa.Float(), nullable=True),
    sa.Column('solar_pct', sa.Float(), nullable=True),
    sa.Column('nuclear_pct', sa.Float(), nullable=True),
    sa.Column('gas_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'timestamp', name='uq_region_timestamp')
    )
    op.create_index('ix_ci_timeseries_region_timestamp', 'ci_timeseries', ['region', 'timestamp'], unique=False)
    op.create_table('hardware_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('hardware_type', sa.String(length=10), nullable=False),
    sa.Column('tdp_watts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hardware_specs')
    op.drop_index('ix_ci_timeseries_region_timestamp', table_name='ci_timeseries')
    op.drop_table('ci_timeseries')
    # ### end Alembic commands ###
